baseurl = "https://blog.lance.tw"
languageCode = "en-us"
title = "Lance Chen"

[author]
    name = "Lance Chen"

[permalinks]

    # Permalink format for pages.
    page = "/:title/"

    # Permalink format for blog posts.
    post = "/article/:title/"

[params]

    # Change the color scheme of Slender.
    # See above for preview and list of color schemes.
    colorscheme = "red"

    # Tagline; HTML accepted here. Keep it concise.
    tagline = ""

    # Footer; Markdown accepted here.
    footer = "Copyright 2016 &copy; Lance Chen"

    # Description and keywords for <meta> tags.
    # Remember to set this for your main page.
    # This will be overridden by whatever is set by the page or post,
    # defined by `description` and `keywords` variables in the front matter
    # of the markdown file.
    description = ""
    keywords = ""

    # Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
    # Remove, comment, or leave blank any field to leave them out.
    email = ""
    github = "https://github.com/Lance0312"
    bitbucket = ""
    twitter = ""
    stackoverflow = ""
    linkedin = "https://tw.linkedin.com/in/lancechentw"
    facebook = ""
    rss = "index.xml"

    # Google Analytics
    # Remove, comment, or leave it blank if you don't have one.
    ganalytics = ""

[menu]

    # Menu for the nav bar.
    # There must always be one item present (e.g. home).
    [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = ""
    weight     = 0

    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
    weight     = 1
